Repository Devcourse-BE6-8-2-Team10/Backend, pull requests merged in 2025-08, with the labels that each got.

#190 [feat] springDoc 설정#1
  src/main/java/com/back/global/springDoc/SpringDocConfig.java
Labels: feat

#193 [refactor] 쿠키 기반의 로그인으로 변경
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/global/security/jwt/JwtFilter.java
  src/main/resources/static/index.html
Labels: refactor

#196 [feat] : security 허용 api추가
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#202 [refactor] CORS 설정에 PATCH 추가
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: refactor

#206 [feat] : 파일 다운로드(이미지 보여주기)
  src/main/java/com/back/domain/files/files/controller/FileDownloadController.java
  src/main/java/com/back/domain/files/files/service/CloudFileStorageService.java
  src/main/java/com/back/domain/files/files/service/FileStorageService.java
  src/main/java/com/back/domain/files/files/service/LocalFileStorageService.java
  src/main/java/com/back/domain/post/dto/PostListDTO.java
  src/main/java/com/back/global/init/PostDataInitializer.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/sample-images/sampleImg1.png
  src/main/resources/sample-images/sampleImg2.png
  src/main/resources/sample-images/sampleImg3.png
  src/main/resources/sample-images/sampleImg4.png
  src/main/resources/sample-images/sampleImg5.png
Labels: feat

#211 Refactor#200 webscoket cors 설정
  .gitignore
  src/main/java/com/back/config/WebsocketConfig.java
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/domain/chat/chat/controller/ChatRestController.java
Labels: refactor

#215 [refactor] 관리자 회원 조회 DTO 변경
  src/main/java/com/back/domain/admin/controller/AdminController.java
  src/main/java/com/back/domain/admin/service/AdminService.java
Labels: refactor

#221 [refactor] 2명의 사용자 모두 채팅방 나갔을 경우에만 DB에서 삭제
  src/main/java/com/back/domain/chat/chat/controller/ChatRestController.java
  src/main/java/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/java/com/back/domain/chat/chat/repository/RoomParticipantRepository.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
Labels: refactor

#224 [refactor] 관리자, 회원 정보 DTO 및 Service 리팩토링
  src/main/java/com/back/domain/admin/dto/request/AdminUpdateMemberRequest.java
  src/main/java/com/back/domain/admin/dto/response/AdminMemberResponse.java
  src/main/java/com/back/domain/admin/service/AdminService.java
  src/test/java/com/back/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
Labels: refactor

#227 [feat] 관리자용 특허 조회, 수정, 삭제 기능 추가
  src/main/java/com/back/domain/admin/controller/AdminController.java
  src/main/java/com/back/domain/admin/dto/request/AdminUpdatePatentRequest.java
  src/main/java/com/back/domain/admin/dto/response/AdminPatentResponse.java
  src/main/java/com/back/domain/admin/service/AdminService.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/test/java/com/back/domain/admin/controller/AdminControllerTest.java
Labels: feat

#230 [feat] 사용자 비밀번호 찾기(초기화) 기능 구현
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/request/FindPasswordRequest.java
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#239 [chore]: 개발 환경 세팅 최종본
  src/main/java/com/back/config/WebsocketConfig.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: chore

#242 [chore]: 백엔드 배포 세팅
  src/main/java/com/back/config/WebsocketConfig.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: chore

#243 [fix] 채팅방 나가고 재생성시 기존 방 으로 입장
  src/main/java/com/back/domain/chat/chat/repository/RoomParticipantRepository.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
Labels: fix
