Repository Devcourse-BE6-8-2-Team10/Backend, pull requests merged in 2025-07, with the labels that each got.

#4 [chore] 기본 설정#1
  .github/workflows/autoIssue.yml
  src/main/java/com/back/BackApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/back/BackApplicationTests.java
Labels: chore

#7 [chore] 로그 출력 색깔 추가#1
  src/main/resources/application.yml
Labels: chore

#16 [feat] chat관련 entity 설정
  src/main/java/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/java/com/back/domain/chat/chat/entity/Message.java
  src/main/java/com/back/domain/chat/chat/entity/RoomParticipant.java
Labels: feat

#23 [feat] Websocket 설정
  src/main/java/com/back/config/WebsocketConfig.java
Labels: feat

#15 Feat#13 첨부파일관련 Entity 생성
  src/main/java/com/back/domain/files/files/entity/Files.java
Labels: feat

#26 [Feat#22] 파일 업로드 관련 DTO생성
  src/main/java/com/back/domain/files/files/dto/FileUploadResponseDto.java
Labels: feat

#24 [feat] Jwt, SecurityConfig 기능 세팅
  build.gradle.kts
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/global/security/auth/CustomUserDetailsService.java
  src/main/java/com/back/global/security/auth/MemberDetails.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/main/java/com/back/global/security/jwt/JwtFilter.java
  src/main/java/com/back/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: feat

#28 [feat] ChatController 생성
  build.gradle.kts
  src/main/java/com/back/domain/chat/chat/controller/ChatController.java
  src/main/java/com/back/domain/chat/chat/dto/MessageDto.java
  src/test/java/com/back/domain/chat/chat/controller/ChatControllerTest.java
Labels: feat

#35 [feat] RsData 구현
  src/main/java/com/back/global/rsData/RsData.java
Labels: feat

#37 [feat]거래 DTO 구현
  src/main/java/com/back/domain/trade/dto/TradeDto.java
  src/main/java/com/back/global/jpa/entity/BaseEntity.java
Labels: feat

#33 [feat] : post entity 생성
  src/main/java/com/back/domain/chat/chat/entity/Message.java
  src/main/java/com/back/domain/files/files/entity/Files.java
  src/main/java/com/back/domain/post/entity/FavoritePost.java
  src/main/java/com/back/domain/post/entity/Post.java
  src/main/java/com/back/domain/trade/entity/Trade.java
Labels: feat

#48 [feat] passwordEncoder 메소드 추가
  src/main/java/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: feat

#47 [feat] : PosrRepository 구현
  src/main/java/com/back/domain/post/repository/PostRepository.java
Labels: feat

#57 [feat] 로그인 요청, 응답 DTO 구현
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/domain/auth/dto/request/MemberLoginRequest.java
  src/main/java/com/back/domain/auth/dto/response/MemberLoginResponse.java
  src/main/java/com/back/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/main/java/com/back/global/rsData/RsData.java
  src/test/java/com/back/domain/auth/AuthControllerTest.java
Labels: feat

#56 [feat] : 찜 게시글 repository 생성
  src/main/java/com/back/domain/post/entity/Post.java
  src/main/java/com/back/domain/post/repository/FavoritePostRepository.java
Labels: feat

#55 [Feat#20] 첨부파일 등록 구현
  src/main/java/com/back/domain/files/files/controller/FilesController.java
  src/main/java/com/back/domain/files/files/dto/FileUploadResponseDto.java
  src/main/java/com/back/domain/files/files/repository/FilesRepository.java
  src/main/java/com/back/domain/files/files/service/FilesService.java
  src/test/java/com/back/domain/files/files/controller/FilesControllerTest.java
Labels: feat

#61 Feat#60
  src/main/java/com/back/domain/chat/chat/controller/ChatController.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
Labels: feat

#64 [feat] 스웨거 UI 기능 추가
  build.gradle.kts
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/main/java/com/back/global/security/jwt/JwtFilter.java
Labels: feat

#66 [Feat#41] 조회 기능 구현, 컨트롤러 리팩터링, 테스트 코드 작성
  src/main/java/com/back/domain/files/files/controller/FilesController.java
  src/main/java/com/back/domain/files/files/repository/FilesRepository.java
  src/main/java/com/back/domain/files/files/service/FilesService.java
  src/test/java/com/back/domain/files/files/controller/FilesControllerTest.java
Labels: feat

#68 [feat] 로그인 기능 구현
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/main/java/com/back/global/security/jwt/JwtTokenProvider.java
  src/test/java/com/back/domain/auth/AuthControllerTest.java
Labels: feat

#73 [feat] 거래 생성#1
  .gitignore
  src/main/java/com/back/domain/post/entity/Post.java
  src/main/java/com/back/domain/trade/controller/TradeController.java
  src/main/java/com/back/domain/trade/entity/Trade.java
  src/main/java/com/back/domain/trade/entity/TradeStatus.java
  src/main/java/com/back/domain/trade/repository/TradeRepository.java
  src/main/java/com/back/domain/trade/service/TradeService.java
  src/main/java/com/back/global/jpa/entity/BaseEntity.java
  src/test/java/com/back/domain/trade/controller/TradeControllerTest.java
Labels: feat

#72 [feat] DataInitializer 기능 구현
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/init/DevDataInitializer.java
  src/main/java/com/back/global/init/TestDataInitializer.java
Labels: feat

#74 [Feat#67] 파일 개별 삭제 구현
  src/main/java/com/back/domain/files/files/controller/FilesController.java
  src/main/java/com/back/domain/files/files/repository/FilesRepository.java
  src/main/java/com/back/domain/files/files/service/FilesService.java
  src/test/java/com/back/domain/files/files/controller/FilesControllerTest.java
Labels: feat

#79 [refactor] 로그인 로직 테스트 및 로그인 상태조회 기능 추가
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
Labels: refactor

#82 [feat] 거래 전체 조회 구현 - 관리자용#1
  src/main/java/com/back/domain/trade/controller/AdmTradeController.java
  src/main/java/com/back/domain/trade/controller/TradeController.java
  src/main/java/com/back/domain/trade/dto/TradePageResponse.java
  src/main/java/com/back/domain/trade/service/TradeService.java
  src/test/java/com/back/domain/trade/controller/AdmTradeControllerTest.java
Labels: feat

#83 [feat] Rq 클래스 구현
  src/main/java/com/back/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/jwt/JwtFilter.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
Labels: feat

#128 [fix] 로그인 로직 오류 수정
  src/main/java/com/back/domain/auth/controller/AuthController.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/main/java/com/back/global/security/auth/CustomUserDetailsService.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/back/domain/member/controller/MemberControllerTest.java
Labels: fix

#137 [feat] 관리자 -> 회원 목록 조회 기능 추가
  src/main/java/com/back/domain/admin/controller/AdminController.java
  src/main/java/com/back/domain/admin/service/AdminService.java
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/global/security/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/back/domain/member/controller/MemberControllerTest.java
Labels: feat

#139 [feat] 관리자용 회원 상세 DTO 구현
  src/main/java/com/back/domain/admin/dto/response/AdminMemberResponse.java
Labels: feat

#146 [refactor] A가 게시글 주인 B가 채팅 신청, C가 A의 게시글에 채팅신청 - A,B : A,C 따로 방 생성
  src/main/java/com/back/domain/chat/chat/repository/ChatRoomRepository.java
  src/main/java/com/back/domain/chat/chat/repository/RoomParticipantRepository.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
Labels: refactor

#150 [feat] 회원 마이페이지 조회
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/response/MemberMyPageResponse.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/test/java/com/back/domain/member/controller/MemberControllerTest.java
Labels: feat

#154 [feat] 회원 정보 수정(비밀번호 변경 포함)
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/back/domain/member/entity/Member.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/test/java/com/back/domain/member/controller/MemberControllerTest.java
Labels: feat

#155 Chore#148 : GCS생성 및 연결 등
  .gitignore
  build.gradle.kts
  src/main/java/com/back/domain/files/files/service/CloudFileStorageService.java
  src/main/java/com/back/domain/post/service/PostService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: chore

#162 [fix] : env관련 추가
  .gitignore
Labels: fix

#165 [feat] 거래 테스트 코드 작성
  src/main/java/com/back/domain/trade/controller/AdmTradeController.java
  src/main/java/com/back/domain/trade/entity/Trade.java
  src/main/java/com/back/domain/trade/service/TradeService.java
  src/main/java/com/back/global/init/TestInitData.java
  src/test/java/com/back/domain/trade/controller/AdmTradeControllerTest.java
  src/test/java/com/back/domain/trade/controller/TradeControllerTest.java
Labels: feat

#167 Feat#149 Redis pub/sub 적용
  build.gradle.kts
  src/main/java/com/back/config/RedisConfig.java
  src/main/java/com/back/domain/chat/chat/controller/ChatWebSocketController.java
  src/main/java/com/back/domain/chat/chat/dto/MessageDto.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
  src/main/java/com/back/domain/chat/redis/listener/RedisMessageSubscriber.java
  src/main/java/com/back/domain/chat/redis/publisher/RedisMessagePublisher.java
  src/main/java/com/back/domain/chat/redis/service/RedisMessageService.java
  src/main/resources/static/index.html
Labels: feat

#168 [feat] 타 회원 정보 조회
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/response/OtherMemberInfoResponse.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/rsData/ResultCode.java
  src/test/java/com/back/domain/member/controller/MemberControllerTest.java
Labels: feat

#171 [refactor] 거래 전반적 리팩토링#1
  src/main/java/com/back/domain/trade/controller/TradeController.java
  src/test/java/com/back/domain/trade/controller/AdmTradeControllerTest.java
Labels: refactor

#174 [chore] CORS 보안 기능 설정 추가
  src/main/java/com/back/global/security/config/SecurityConfig.java
Labels: chore

#177 Refactor#176
  src/main/java/com/back/domain/chat/chat/controller/ChatRestController.java
  src/main/java/com/back/domain/chat/chat/dto/MessageDto.java
  src/main/java/com/back/domain/chat/chat/entity/ChatRoom.java
  src/main/java/com/back/domain/chat/chat/service/ChatService.java
Labels: refactor
